### PR TITLE
android-build: Update base image and Android build tools

### PR DESCRIPTION
**Pull request by ilammy**
- Sync with updates in https://github.com/cossacklabs/themis for upcoming Themis 0.15
- Update base system to Ubuntu 22.04 LTS
- Update misc. dependencies (e.g., Golang)

### CODE REVIEW

**Comment by Lagovas** [comment]
can you remind where we use this image? as I understand, for themis we use github ci with their own images.

**Comment by ilammy** [comment]
> can you remind where we use this image?

Supposedly, whoever publishes AndroidThemis releases should be using this image for building them. I'm not aware how well automation penetrated and whether *this* image is actually used, or there's something else in BuildBot.

This image is also the one [used in documentation](https://docs.cossacklabs.com/themis/languages/kotlin/installation-android/#building-latest-version-from-source) on how to build AndroidThemis from source.

It is not used by GitHub CI. Those builds use the base system directly, using preinstalled SDK, NDK, etc.

**Comment by Lagovas** [comment]
did you try to build using updated image and instructions from docs? to be sure that it will not be broken after update. or we need to update docs?

**Comment by ilammy** [comment]
> did you try to build using updated image and instructions from docs?

Sure. It worked for me.

> or we need to update docs?

The only change after AndroidThemis 0.15 release would be

```diff
 The resulting Android library (AAR) will be placed into
-`src/wrappers/themis/android/build/outputs/aar/android.aar`.
+`src/wrappers/themis/android/build/outputs/aar/android-release.aar`.
 You can then rename it and add to your project.
```

**Review by vixentael — APPROVED** [review]

**Comment by vixentael** [comment]
> The only change after AndroidThemis 0.15 release would be

we plan to release 0.15? Hm :)
I thought it gonna be 0.14.XX

**Comment by vixentael** [comment]
Taking about the docs, pls take a look at this draft PR.
https://github.com/cossacklabs/product-docs/pull/265/files

Are these changes enough?

**Review by Lagovas — APPROVED** [review]

**Comment by ilammy** [comment]
> we plan to release 0.15? Hm :)
> I thought it gonna be 0.14.XX

However you want to manage that release. If a hotfix for Android would become necessary, I ~~believe~~ hope the old code would still build in the old Docker image. This doesn't sound like a hard thing to backport to `release/0.14` branch though.

> Taking about the docs, pls take a look at this draft PR.
>
> Are these changes enough?

Yes. Thank you for updating the version as well!

**Pull request merged**
