### PR TITLE
build: initial Dockerfile for Ubuntu 18.04

### PR DESCRIPTION
**Pull request by ilammy**
An image for running static and dynamic analysis of Themis on CI. We're starting fairly minimal but with the recent compilers.

This Dockerfile corresponds to the `cossacklabs/themis-ci:analyze` tag.

### CODE REVIEW

**Review by vixentael — APPROVED** [review]
i totally like and approve the overall idea.

if @shadinua has some specific requirements in mind – i'm sure he will kind to share them

**Comment by shadinua** [comment]
Sure, generally I support the idea to have useful pre-built tools for developing.

But there are some questions:
* For exactly what purposes this image was built in the long run? Perhaps, depending on the answer, I'd have additional suggestions.
* If we need just an image with pre-installed compilers, there are too many similar ones. Why should we have to build another one?
* Why Ubuntu was used as base image? Probably, if we need a more stable platform, we could use debian? Of course, if we need latest package-base distro, Ubuntu LTS is a good choice. In that case we have to bear in mind that Ubuntu have some differences from classical Linux approaches.
* While it is a general purpose image, I'd suggest to place it somewhere like a `general/ubuntu_bionic_build/Dockerfile` instead of `themis_ci/analyze/Dockerfile`.

**Comment by ilammy** [comment]
@shadinua, thank you for your input.

> For exactly what purposes this image was built in the long run?

Right now I'd like to use this image for running Themis core tests with run-time sanitizers, compiling the source code with the latest compilers so that we get all the warnings in the world. Later I imagine using this image for running other kinds of dynamic and static analysis of Themis. The main user of it will be the CI builders, but the developers can also use the image for debugging right away if the build breaks for some reason.

> Why should we have to build another [image]?

I'd like to have an image that we control for the sake of predictability and maintainability of CI builds. Public Docker images are cheap to create, build and host, so using a specific image called `cossacklabs/themis-ci` immediately communicates its purpose, ships all the tools, libraries and dependencies the _we_ need, and gives us a stable platform that will not suddenly update or disappear.

> Why Ubuntu was used as base image?

Mostly because I'm personally more comfortable with Debian-based distributions. I'd like to have a reasonably stable platform, but with the latest compilers, so I went for Ubuntu 18.04 LTS instead of alternatives.

|Compiler|Debian 9 (stable)|Debian 10 (testing)|Ubuntu 18.04 LTS|Ubuntu 18.10|trunk|
|-|-|-|-|-|-|
|gcc|6.3|8.2|7.3|8.2|8.3|
|clang|4.0|7.0|6.0|7.0|7.0.1|

Debian 10 is scheduled for release somewhere in summer 2019. However, it's already soft-frozen so we could try using the (current) testing branch instead of Ubuntu 18.04, I think.

Ubuntu 18.10 has a newer compiler, but its support will be dropped in July 2019 so I'd rather wait for 19.04 instead.

> While it is a general purpose image [...]

I do not intend this to be a general-purpose image for testing anything on Ubuntu 18.04 specifically. Rather, this is an image for building Themis on CI infrastructure for the purpose of analysis. Hence the name of the image `themis-ci` and the tag `analysis`.

**Review by shadinua — APPROVED** [review]
@ilammy, thank you for explain!

I would not like to expand this review to the size of the discussion of the construction of a bicycle shed. :-)

However, since we are talking not only about the container itself but rather about the approach to the organization of the repository, I'd like to suggest where possible, comply concordance between the names and contents. 

So, if the container is de facto just a platform with a compiler and can be used for a wide range of tasks, I think it’s better to reflect this in the title.

Thank you!

**Comment by ilammy** [comment]
After discussion with @shadinua we have agreed that a more general name would be better.

This image can be used as a general-purpose building platform on Ubuntu 18.04 so let's name it `cossacklabs/build:ubuntu-bionic`

**Review by vixentael — APPROVED** [review]

**Pull request merged**
